---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskly-frontend
  labels:
    app: taskly
    component: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taskly
      component: frontend
  template:
    metadata:
      labels:
        app: taskly
        component: frontend
    spec:
      containers:
      - name: taskly-frontend
        image: "sudomateo/taskly-frontend:6f25cec03dfe5edb2196d1bfd558adbec3fa94d6"
        ports:
          - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: taskly-frontend
spec:
  selector:
    app: taskly
    component: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskly-backend
  labels:
    app: taskly
    component: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taskly
      component: backend
  template:
    metadata:
      labels:
        app: taskly
        component: backend
    spec:
      containers:
      - name: taskly-backend
        image: "sudomateo/taskly-backend:6f25cec03dfe5edb2196d1bfd558adbec3fa94d6"
        ports:
          - containerPort: 3030
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3030
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3030
          initialDelaySeconds: 3
          periodSeconds: 3

---
apiVersion: v1
kind: Service
metadata:
  name: taskly-backend
spec:
  selector:
    app: taskly
    component: backend
  ports:
    - protocol: TCP
      port: 3030
      targetPort: 3030

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: taskly
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              service:
                name: taskly-frontend
                port:
                  number: 80
            pathType: Prefix
          - path: /api
            backend:
              service:
                name: taskly-backend
                port:
                  number: 3030
            pathType: Prefix
